name: iOS Build (Switch2Launcher + Dolphin)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      # 1. Install tools
      - name: Install dependencies
        run: |
         brew install cmake ninja unzip

      # 2. Unzip Switch2Launcher project
      - name: Unzip Switch2Launcher Project
        run: |
         unzip Switch2Launcher_Xcode_DolphinFull.zip -d Switch2LauncherProject

      # 3. Clone Dolphin iOS
      - name: Clone Dolphin iOS
        run: |
         git clone https://github.com/oatmealdome/dolphin.git
         cd dolphin
         git submodule update --init --recursive
